### ISSUE TITLE
Any experience/concerns with orthanc ? 

### ISSUE THREAD

**Issue by yarikoptic** [neurolabusc/dcm_qa_agfa#1]
Given that there are problems unraveled with dcm4che, for our next deployment/project we are considering https://www.orthanc-server.com/  . I wondered if you had any experience, have anything to say good/bad?

Cheers,

**Comment by neurolabusc** [comment]
Sorry I have no experience. It does sound promising. I like dcmtk, but like fsl and free surfer it is free but not truly open source.

**Comment by yarikoptic** [comment]
Thank you Chris!

**Comment by yarikoptic** [comment]
FWIW -- orthanc is "open core" AFAIK -- thus most of the components are even present in Debian proper (so as free as it gets ;)), extra functionality (e.g. some integrations with proprietary systems) indeed might be non-free, may be only with few pieces removed although seems most of them seems to be removed likely just because of embedding libraries packaged separately, ... from [debian/copyright](https://metadata.ftp-master.debian.org/changelogs//main/o/orthanc/orthanc_1.10.1+dfsg-2_copyright):

```
Format: https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/
Upstream-Name: Orthanc
Upstream-Contact: Sebastien Jodogne <s.jodogne@gmail.com>
Source: https://hg.orthanc-server.com/orthanc/
Files-Excluded:
        OrthancServer/OrthancExplorer/libs/date.js
        OrthancServer/OrthancExplorer/libs/images/ajax-loader*
        OrthancServer/OrthancExplorer/libs/images/icons-*
        OrthancServer/OrthancExplorer/libs/jquery.min.js
        OrthancServer/OrthancExplorer/libs/jquery.mobile.min.css
        OrthancServer/OrthancExplorer/libs/jquery.mobile.min.js
        OrthancFramework/Resources/ThirdParty/patch/*
        OrthancFramework/Resources/ThirdParty/icu/*
        OrthancFramework/Resources/ThirdParty/VisualStudio/*

```
